language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install --upgrade pip
  - pip install .[testing]
script: nosetests
